
DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS stars CASCADE;
DROP TABLE IF EXISTS folks CASCADE;
DROP TABLE IF EXISTS repos CASCADE;

CREATE TABLE authors (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author TEXT
);

CREATE TABLE languages(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  language_name TEXT 
);

CREATE TABLE stars(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  stars TEXT
);

CREATE TABLE forks(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  fork TEXT 
);

CREATE TABLE repos (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  repo_name TEXT 
);
